### ISSUE TITLE
not work like 

### ISSUE THREAD

**Issue by org-lib** [marianogappa/sqlparser#12] opened 2022-07-12 06:48 UTC
SELECT a, b, c FROM tab a WHERE e = '1' AND f > '2'

------------------------------------------------------->>>

SELECT a, b, c FROM tab a WHERE e = '1' AND f > '2'
                        ^
expected WHERE
2022/07/12 14:47:23 expected WHERE

**Comment by marianogappa** [comment] 2022-07-12 11:23
Hey! Thanks for raising this issue. The problem is that this parser does not support aliases, so `tab a` is not supported. It would probably work if you call it just `tab`.

This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!

**Closed as completed by marianogappa** 2022-07-12 11:23 UTC
