### ISSUE TITLE
update where [in] condition parse error

### ISSUE THREAD

**Issue by BlackSinny** [marianogappa/sqlparser#15] opened 2023-10-17 01:41 UTC
- sql
```sql
UPDATE t1 SET change_by = '1' WHERE id = '3' AND status IN (1,2,3)
```

when i run this test case , code retrun **at WHERE: unknown operator**
![image](https://github.com/marianogappa/sqlparser/assets/38745744/8aa949a0-1f3a-4309-8216-b6f353091b93)
![image](https://github.com/marianogappa/sqlparser/assets/38745744/81389059-c67c-416e-887f-13ee6c985c21)

**Comment by marianogappa** [comment] 2023-10-17 10:31
Hey! Thanks for raising this issue. The problem is that this parser does not support the IN clause.

This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!

**Closed as completed by marianogappa** 2023-10-17 10:31 UTC
