### ISSUE TITLE
【Help】How to handle multi-layer nested syntax？

### ISSUE THREAD

**Issue by wwhai** [marianogappa/sqlparser#14] opened 2023-05-31 06:54 UTC
```sql
SELECT * from
	(SELECT name from csv where addr='england')
where name='horns'
```

**Comment by marianogappa** [comment] 2023-05-31 10:47
Hey! Thanks for raising this issue. The problem is that this parser does not support subqueries.

This isn't actually meant to be a complete SQL parser. It's part of a blog meant to teach people about LL1 parsers.

Here's the blog:
https://marianogappa.github.io/software/2019/06/05/lets-build-a-sql-parser-in-go/

However, every once in a while someone actually uses it for something, so I'm still happy to merge PRs, unless they complicate the code too much.

For now, I'll close this. Thanks anyway, though!

**Closed as completed by marianogappa** 2023-05-31 10:47 UTC
